#!/bin/sh

set -eu

GEMFILE="$1"

gem install bundler-audit

case $GEMFILE in

  gemfiles/rails7.1.gemfile)
    IGNORED=""
    ;;
  gemfiles/rails7.2.gemfile)
    IGNORED=""
    ;;
  gemfiles/rails8.0.gemfile)
    IGNORED=""
    ;;
  *)
    echo unsupported gemfile: $GEMFILE
    exit 1
    ;;
esac

if [ -n "$IGNORED" ]; then
  echo "::warning:: Ignored vulnerabilities: $IGNORED"
  bundle-audit check --update --gemfile-lock $GEMFILE.lock --ignore $IGNORED
else
  bundle-audit check --update --gemfile-lock $GEMFILE.lock
fi
