#!/bin/sh

set -eu

GEMFILE="$1"

gem install bundler-audit

case $GEMFILE in

  gemfiles/rails6.0.gemfile)
    IGNORED="CVE-2023-28120 CVE-2022-44566 CVE-2023-22796"
    ;;
  gemfiles/rails6.1.gemfile)
    IGNORED=""
    ;;
  gemfiles/rails7.0.gemfile)
    IGNORED=""
    ;;
  *)
    echo unsupported gemfile: $GEMFILE
    exit 1
    ;;
esac

if [ -n "$IGNORED" ]; then
  echo "::warning:: Ignored vulnerabilities: $IGNORED"
  bundle-audit check --update --gemfile-lock $GEMFILE.lock --ignore $IGNORED
else
  bundle-audit check --update --gemfile-lock $GEMFILE.lock
fi
