name: Continuous Integration
on: push

jobs:
  specs:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        ruby:
          - '3.3'
          - '3.4'
        gemfile:
          - gemfiles/rails7.1.gemfile
          - gemfiles/rails7.2.gemfile
          - gemfiles/rails8.0.gemfile
    env:
      BUNDLE_GEMFILE: ${{ matrix.gemfile }}
    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
      - name: rake test
        run: bundle exec rake test

  specs_successful:
    name: Specs passing?
    needs: specs
    if: always()
    runs-on: ubuntu-latest
    steps:
      - run: |
          if ${{ needs.specs.result == 'success' }}
          then
            echo "All specs pass"
          else
            echo "Some specs failed"
            false
          fi

  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
      - run: bundle exec rubocop
