name: Continuous Integration
on: push

jobs:
  specs:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        ruby:
          - '3.3'
          - '3.4'
        gemfile:
          - gemfiles/rails7.1.gemfile
          - gemfiles/rails7.2.gemfile
          - gemfiles/rails8.0.gemfile
        include:
          - {ruby: '3.3', gemfile: 'gemfiles/rails7.0.gemfile'}
    env:
      BUNDLE_GEMFILE: ${{ matrix.gemfile }}
    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
      - name: rake test
        run: bundle exec rake test
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.3'
          bundler-cache: true
      - name: rake fmt
        run: bundle exec rake fmt
