name: Continuous Integration
on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master
jobs:
  specs:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        ruby:
          - 2.6.6
          - 2.7.1
        gemfile:
          - gemfiles/rails4.2.gemfile
          - gemfiles/rails5.0.gemfile
          - gemfiles/rails5.1.gemfile
          - gemfiles/rails5.2.gemfile
        exclude:
          - {ruby: 2.7.1, gemfile: 'gemfiles/rails4.2.gemfile'} # NoMethodError: undefined method `new' for BigDecimal:Class
    env:
      BUNDLE_GEMFILE: ${{ matrix.gemfile }}
    steps:
      - uses: zendesk/checkout@v2
      - uses: zendesk/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
      - name: test
        run: bundle exec rake test
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: zendesk/checkout@v2
      - uses: zendesk/setup-ruby@v1
        with:
          ruby-version: 2.6.6
          bundler-cache: true
      - name: rubocop
        run: bundle exec rubocop
