name: Security
on: [push]
jobs:
  main:
    name: bundle-audit
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        gemfile:
          - gemfiles/rails7.1.gemfile
    steps:
    - uses: actions/checkout@v4
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.3'
    - name: Checking ${{ matrix.gemfile }}
      run: ./script/bundle-audit ${{ matrix.gemfile }}
