name: Security
on: [push]
jobs:
  main:
    name: bundle-audit
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        gemfile:
          - gemfiles/rails4.2.gemfile
          - gemfiles/rails5.0.gemfile
          - gemfiles/rails5.1.gemfile
          - gemfiles/rails5.2.gemfile
          - gemfiles/rails6.0.gemfile
          - gemfiles/rails6.1.gemfile
    steps:
    - uses: zendesk/checkout@v2
    - uses: zendesk/setup-ruby@v1
      with:
        ruby-version: 2.6.6
    - name: Checking ${{ matrix.gemfile }}
      run: ./script/bundle-audit ${{ matrix.gemfile }}
