name: Security
on: [push]
jobs:
  main:
    name: bundle-audit
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        gemfile:
          - gemfiles/rails6.0.gemfile
          - gemfiles/rails6.1.gemfile
          - gemfiles/rails7.0.gemfile
    steps:
    - uses: zendesk/checkout@v4
    - uses: zendesk/setup-ruby@v1
      with:
        ruby-version: 3.1
    - name: Checking ${{ matrix.gemfile }}
      run: ./script/bundle-audit ${{ matrix.gemfile }}
